FROM tensorflow/serving:latest-devel as build_image

FROM alpine:latest

RUN apk add --no-cache -y \
        ca-certificates

COPY --from=build_image /usr/local/bin/tensorflow_model_server /usr/bin/tensorflow_model_server
COPY model_trained/export/exporter/ /model

EXPOSE 9000

ENTRYPOINT tensorflow_model_server --rest_api_port=9000 --model_name=default --model_base_path=/model/
